### ISSUE TITLE
About transcriptomics normalization

### ISSUE THREAD

**Issue by martingarridorc** [PayneLab/cptac#12]
Hello,

First of all, congratulations and thank you for developing this package!. I think is a very useful tool for those of us working on multi-omics data integration. Regarding the transcriptomics, I have some questions

1. RNA-Seq data is normalized in the same way for all the cohorts? Can you please share the protocol to obtain such normalized values? 

2. Are they RPKMs? CPMs? 

3. Do the absent values correspond to zero counts situations?

Thanks

**Comment by samuelpayne** [comment]
Thanks for using the package. This is an API for a variety of datasets that were sometimes created using different pipelines. The best answer that I can give you is to look at the method details in the original publication. For example, if you are curious about the ccRCC RNA-seq data, you should look in the ccRCC publication. Using  cptac.list_datasets() command, you will see that ccRCC was published here (https://www.ncbi.nlm.nih.gov/pubmed/31675502).
1. not really. Each paper is it's own.
2. individual to each cohort
3. data is often scaled to be a 'normal' distribution centered at zero. so a zero value represents the 'average' of the disease specific cohort. negative numbers are less than average, positive numbers are above average. but, as said, some cohorts were left with just raw RPKM, FPKM, or RSEM numbers. Best to read the paper methods.

**Comment by caleb-lindgren** [comment]
Sorry for the late reply. As far as what they use for centering, the best place to find the answer would again be in the methods section for the paper corresponding to the dataset you're using. 

If you want the original raw instrument data files, you can download them from the CPTAC Data Portal at <https://cptac-data-portal.georgetown.edu/>. Just be aware that the files are very large. The raw mass spectrometry proteomic data is hosted directly on this site, and it also has links to access each project's genomic data on the NCI Genomic Data Commons, and imaging data from NCI's The Cancer Imaging Archive.

**Comment by martingarridorc** [comment]
In case it is useful for someone, as I wanted to perform an analysis across cohorts, I had to normalize RNA-Seq data by myself. With CPTAC proteomic TMT10 data, this is done thanks to the different facilities following the same protocol, but with RNA-Seq data,  one needs to download raw counts from CPTAC and cross the IDs with the ones at the proteomic tables.
