### ISSUE TITLE
Data questions

### ISSUE THREAD

**Issue by SaharAlkhairy** [PayneLab/cptac#15]
I had a couple of questions:

1) I understand that the "ReferenceIntensity" is subtracted from the intensity of the samples for transcriptomic and proteomic data. Is the reference intensity an external sample? Or is it an aggregated statistic from normal samples?
2) I wasn't able to find any data normalization within the code. Was the data previously normalized? If so, what normalization method did they use?
3) Is the data in log ratio?
4) For the data that requires a password, how would one go about obtaining permission and password?

Thanks

**Comment by samuelpayne** [comment]
Thanks for the interest. Our package is merely presenting data that is published in various CPTAC papers. The best information on details of the data analysis pipelines can be found in the original papers. This is where you'll find answers about log ratios and normalizations.  You can find pubmed links with

cptac.list_datasets()

The passworded data is only available to those within the CPTAC consortium. It will become available upon publication.

Thanks
