### ISSUE TITLE
how do you process the CPTAC spectral counts data?

### ISSUE THREAD

**Issue by ZihaoXingUP** [PayneLab/cptac#18]
thanks for you giving the cptac data. i see your cptac data aren't the counts data, i want to know which method you used when you processed the CPTAC spectral counts  data .

**Comment by samuelpayne** [comment]
All the data in CPTAC is TMT isobaric labeled data. Spectrum counts cannot
be used with this kind of multiplexing.

The quantitative data has been processed to achieve the numbers you see.
The best place to learn about the method for that is in the link to
publications.

**Comment by caleb-lindgren** [comment]
You can access the publications associated with the different datasets using this code:
```
import cptac
cptac.list_datasets()
```
We provide the same tables that were used in these publications. The methods section of each paper will describe the specifics of how the data was processed for that dataset.
