### ISSUE TITLE
cptac.utils.get_frequently_mutated() ValueError

### ISSUE THREAD

**Issue by nanel96** [PayneLab/cptac#21]
When I run the cptac.utils.get_frequently_mutated function, I receive the following error: "ValueError: columns overlap but no suffix specified: Index(['Gene'], dtype='object', name='Name')"

It appears to be an issue with using the pandas.join() function in the code. 

I get the same error when I try it with Luad, Hnscc, Lscc, Endometrial, and Ccrcc

Here is my code: 

`import cptac
import pandas as pd
import cptac.utils as ut

ccrcc = cptac.Ccrcc()

ccrcc_mutation_df = ut.get_frequently_mutated(ccrcc)`

[Notebook with error message](https://github.com/PayneLab/pancancerProteinMRNA/blob/master/notebook_steps/Find%20Top%205%20Mutated%20Genes.ipynb)

**Comment by caleb-lindgren** [comment]
Hmm, that's interesting. I downloaded your notebook and ran it on my machine, and there weren't any problems. Which versions of cptac and pandas do you have installed?

**Comment by caleb-lindgren** [comment]
Are you still having this issue? If it's not a problem anymore I'll just close it.

**Comment by nanel96** [comment]
@caleb-lindgren I am using cptac v 0.8.8 and pandas 1.0.5 -- also, yes I am still having the issue

**Comment by nanel96** [comment]
@caleb-lindgren I updated to pandas v 1.2.3 and that appears to have fixed the issue.
