### ISSUE TITLE
Document published CPTAC studies and those implemented in package

### ISSUE THREAD

**Issue by sooheon** [PayneLab/cptac#24]
Thanks for this great resource. I see devdocs has instructions on contributing datasets, it would be very helpful to see a roadmap of currently available CPTAC studies (looks like 58: https://cptac-data-portal.georgetown.edu) vs those implemented in this package. 

This can help coordinate contributions as well as allow discoverability to those unfamiliar with CPTAC.

**Comment by samuelpayne** [comment]
So the datasets to be included in the package are all the cptac datasets. You can see the ones currently available by doing a cptac.list_datasets(). As CPTAC generates more datasets, we put them into the package. right now, we have all the cptac datasets included.

also - the devdocs are mostly for internal developer use, instructions left for those who maintain the package.
