### ISSUE TITLE
Request for LSCC data

### ISSUE THREAD

**Issue by srithegreat** [PayneLab/cptac#25]
HI,

I see that the LSCC data is published now. Do you have any plan to make that data available soon?

Thanks,
Srikanth

**Comment by caleb-lindgren** [comment]
Yes thanks for pointing that out! It should be freely accessible now.

**Comment by caleb-lindgren** [comment]
Meaning, we edited the permissions so you no longer need a password, so that should all be working. Let us know if you run into any issues with it.

**Comment by srithegreat** [comment]
All good. Thanks for the prompt action.
