### ISSUE TITLE
the threshold about wgs_somatic_cnv_per_gene data

### ISSUE THREAD

**Issue by zihaoxingstudy1** [PayneLab/cptac#28]
hello, i see the wgs_somatic_cnv_per_gene data in gbm  are continuous data. I want to know how to determine the threshold and define which ranges belong to copy number amplification and copy number deletion

**Comment by caleb-lindgren** [comment]
In the [endometrial cancer flagship paper](https://pubmed.ncbi.nlm.nih.gov/32059776/), they recommend using a cutoff of 0.2 for the log ratio CNV data. Anything over +0.2 would be a copy number amplification, and anything below -0.2 would be a copy number deletion.
