### ISSUE TITLE
With new framework, can't find all files

### ISSUE THREAD

**Issue by sgosline** [PayneLab/cptac#35]
Given the new changes, the package cannot find the ccrcc miRNA files, even though they claim to exist.  These commands repro my error:
`import cptac`
`dat=cptac.Ccrcc()`
`dat.list_data_sources()`
`dat.get_miRNA('washu')`

I've attached a screenshot of the error
<img width="754" alt="Screenshot 2023-08-16 at 7 52 07 AM" src="https://github.com/PayneLab/cptac/assets/1847866/a130c2b3-4bfe-44c2-9ba7-8fcf02bb9a21">

**Comment by sgosline** [comment]
I'm struggling to get any miRNA data (for other tumor types).

**Comment by bm600** [comment]
Hey thanks for using CPTAC, we are working on the bug and it should be released soon

**Comment by samuelpayne** [comment]
We pushed a new update 1.5.1 which has the miRNA data (and also BCM as a source). Let me know i that doesn't work

**Comment by sgosline** [comment]
Thanks, I’ll check it out later this week. Currently bouncing back to another project, which raised another issue.

-sara

---------------------------------------------------
Sara JC Gosline, PhD
Senior Scientist
Team Lead, Software & Algorithms
Pacific Northwest National Laboratory
Seattle,  WA
---------------------------------------------------

From: Sam Payne ***@***.***>
Date: Monday, September 11, 2023 at 11:26 AM
To: PayneLab/cptac ***@***.***>
Cc: Gosline, Sara J ***@***.***>, Author ***@***.***>
Subject: Re: [PayneLab/cptac] With new framework, can't find all files (Issue #35)
Check twice before you click! This email originated from outside PNNL.


We pushed a new update 1.5.1 which has the miRNA data (and also BCM as a source). Let me know i that doesn't work

**Comment by sgosline** [comment]
I dont have the power to re-open, but this fails for ovarian: 
```
cptac error: Requesting data failed with the following error: 404 Client Error: NOT FOUND for url: https://zenodo.org/api/files/153885f4-b0e8-4090-872c-20f36635b42a/washu-ov-miRNA-OV_precursor_miRNA_combined.tsv.gz (/Users/gosl241/Library/CloudStorage/OneDrive-PNNL/Documents/GitHub/candleDataProcessing/cptac/getCptacData.py, line 307)
```
