### ISSUE TITLE
how to download the transcript-level not the gene-level data from  CPTAC?

### ISSUE THREAD

**Issue by zihaoxingstudy1** [PayneLab/cptac#36]
i only can download the gene-level RNAseq data of TCGA or CPTAC, I want to know how to download the transcript-level not the gene-level data from TCGA or CPTAC?

**Comment by samuelpayne** [comment]
Hopefully this will be helpful. 
1. The data we serve through this API is only CPTAC. We do not serve TCGA data. TCGA data can be found with TCGABiolinks - https://bioconductor.org/packages/release/bioc/html/TCGAbiolinks.html. 
2. By reading the method/pipeline description in the manuscript's supplement (https://bioconductor.org/packages/release/bioc/html/TCGAbiolinks.html), you can see if there is transcript level data. For example, the BCM pipeline picks only a single representative transcript per gene. The RNA quantification from the Broad describes isoform specific quantification. Their data can be downloaded most easily at https://pdc.cancer.gov/pdc/cptac-pancance, see the file RNA_Broad_v1.zip
