### ISSUE TITLE
tutorial is not compatible with current release

### ISSUE THREAD

**Issue by sky1ove** [PayneLab/cptac#38]
Hi, in the tutorial 1:

cptac.download(dataset="endometrial")

this code just doesn't work, as the download function needs input of cancer, source, dtype and data_file.

And en.list_data() seems also change.

Please modify the tutorials as the functions change.

---
update: 

Just found your updated tutorials in your notebooks folder. May I ask if they've been completed or there's more modifications or addition going on?

**Comment by bm600** [comment]
Yes they are completed and error-free as far as we know. If you find any errors please let us know and we'll take care of it. Thanks and we hope you're finding CPTAC useful!

**Comment by old-rob** [comment]
There may exist multiple versions of the tutorials. The website at https://paynelab.github.io/cptac/tutorial01_data_intro.html seems to be out of date, in which case you could generate new html files from the updated jupyter notebooks and use those to replace the files under cptac/docs - that should help everyone find the correct instructions
