### ISSUE TITLE
make CPTAC_BASE_DIR configurable

### ISSUE THREAD

**Issue by sgosline** [PayneLab/cptac#39]
I created a Docker image of the old version of the package that downloaded the datasets explicitly. Now that the datasets are downloaded automatically, I can't use the package in Docker since the file system is read only by default. It appears that the `CPTAC_BASE_DIR` variable is hard coded based on the package installation. Is there a way to override this so I can use this package in Docker? Maybe check for an environment variable first? Or allow me to pass in a path? I need to point all data downloads to `/tmp/`. Here is an example: https://github.com/PNNL-CompBio/decomprolute/tree/main/mRNAData

**Comment by sgosline** [comment]
I just thought of a potential workaround - is there a way to force the dataset downloads, like I did in this script [here](https://github.com/PNNL-CompBio/decomprolute/blob/main/mRNAData/getAllDatasets.py)? This functionality went away, but by running the download at the docker-build time i was able to not have to write anything during run time. Thoughts?

**Comment by sabmel** [comment]
Hi there! I don't know if this would completely fix the issue, but in the newest version, we have a cptac.download_cancer('[cancer]') function that just runs through and downloads all of the data for the given cancer. I hope that helps!

**Comment by sgosline** [comment]
Thanks! Any reason why this replaced the previously documented `download` function? Trying to keep up with these changes has been a challenge.

**Comment by sgosline** [comment]
I tried to run it like I did before, and I get this error: 
```
46.94 cptac error: Requesting data failed with the following error: 429 Client Error: TOO MANY REQUESTS for url: https://zenodo.org/api/files/153885f4-b0e8-4090-872c-20f36635b42a/broad-brca-mapping-gencode.v34.GRCh38.genes.collapsed_only.gtf.gz (/bin/getAllDatasets.py, line 8)
```

**Comment by sabmel** [comment]
Hi Sara,

We changed how data was stored, accessed, and downloaded, so the previous
download function is now obsolete. I will look into your other error as
soon as possible.

Thank you,

Sabrina Smith

**Comment by sabmel** [comment]
I'm sorry; what was the command that ran to get that error again?
