### ISSUE TITLE
i want to know the difference between the Cell paper pan-cancer cptac data and your processed data.

### ISSUE THREAD

**Issue by zihaoxingstudy1** [PayneLab/cptac#43]
i see the cell pan-cancer cptac paper data [cptac-pancancer](https://pdc.cancer.gov/pdc/cptac-pancancer) do not have OV cancer types ,but your cptac latest version data have OV pancer types. in your cptac older version, it have KIRC cancer cptac data, but now , it do not have the KIRC cancer data in your cptac latest version.

**Comment by samuelpayne** [comment]
by KIRC do you mean ccRCC?

**Comment by zihaoxingstudy1** [comment]
i mean kidney cancer in the CPTAC. 
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Sam ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/26/2023 00:22
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [PayneLab/cptac] i want to know the difference between the Cell paper pan-cancer cptac data and your processed data. (Issue #43)
        
      
    
  

by KIRC do you mean ccRCC?

**Comment by bm600** [comment]
You can see the available cancer options by inputting cptac.get_cancer_info(). It will print a dictionary of the available types. In the latest version kidney cancer (clear cell renal cell carcinoma) is abbreviated as ccrcc. Hope that helps!

**Comment by zihaoxingstudy1** [comment]
thanks. i download the BCM source ccrcc proteomics data . it only has 104 tumor samples in your data.
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/29/2023 01:16
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [PayneLab/cptac] i want to know the difference between the Cell paper pan-cancer cptac data and your processed data. (Issue #43)
        
      
    
  

You can see the available cancer options by inputting cptac.get_cancer_info(). It will print a dictionary of the available types. In the latest version kidney cancer (clear cell renal cell carcinoma) is abbreviated as ccrcc. Hope that helps!

**Comment by samuelpayne** [comment]
we'll look into that.
