### ISSUE TITLE
CCRCC cancer proteomics data do not have normal tissue type in your latest cptac data

### ISSUE THREAD

**Issue by zihaoxingstudy1** [PayneLab/cptac#44]
CCRCC cancer proteomics data do not have normal tissue type in your latest cptac data

**Comment by sabmel** [comment]
Hello! The normal tissue data should be at the bottom of the data frame, appended with a .N. Can you please let us know which proteomics source you were pulling from?

**Comment by zihaoxingstudy1** [comment]
i pulling the BCM cptac ccrcc proteomics dataset. but it doesn't have normal tissue smaples. it only has 104 tumor samples in your data.
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Sabrina ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/28/2023 07:30
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [PayneLab/cptac] CCRCC cancer proteomics data do not have normal tissue type in your latest cptac data (Issue #44)
        
      
    
  

Hello! The normal tissue data should be at the bottom of the data frame, appended with a .N. Can you please let us know which proteomics source you were pulling from?

**Comment by sabmel** [comment]
Thank you for letting us know! You are right, and that was a mistake on our
end. We are working to update the bcm proteomics datasets to include both
tumor and normal. I appreciate your patience, and feel free to utilize the
'umich' source until we update the package (it has normal samples).

**Comment by bm600** [comment]
Hello @zihaoxingstudy1. We've just updated the package to include all available normal-tissue samples with the Baylor (bcm) source. This is available in v1.5.3. Thanks for bringing this to our attention and thanks for using the package! Let us know if you have any other issues.

**Comment by zihaoxingstudy1** [comment]
thanks ,i will upgrade the cptac and download the latest  bcm source data
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/3/2023 07:31
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [PayneLab/cptac] CCRCC cancer proteomics data do not have normal tissue type in your latest cptac data (Issue #44)
        
      
    
  

Hello @zihaoxingstudy1. We've just updated the package to include all available normal-tissue samples with the Baylor (bcm) source. This is available in v1.5.3. Thanks for bringing this to our attention and thanks for using the package! Let us know if you have any other issues.

**Comment by zihaoxingstudy1** [comment]
The ucec umich acetylproteomics data are note a suitable data frame format,and there are variable names in the middle of the file.
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Sabrina ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/30/2023 11:39
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [PayneLab/cptac] CCRCC cancer proteomics data do not have normal tissue type in your latest cptac data (Issue #44)
        
      
    
  

Thank you for letting us know! You are right, and that was a mistake on our

end. We are working to update the bcm proteomics datasets to include both

tumor and normal. I appreciate your patience, and feel free to utilize the

'umich' source until we update the package (it has normal samples).
