### ISSUE TITLE
Error in cancer.py file

### ISSUE THREAD

**Issue by janamace** [PayneLab/cptac#45]
Hello,

After installing the cptac package I am having this problem. can you help me?

import cptac
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-d93fde8d488c> in <module>
----> 1 import cptac

~\anaconda3\lib\site-packages\cptac\__init__.py in <module>
     30 
     31 # Dataset imports
---> 32 from cptac.cancers.brca import Brca
     33 from cptac.cancers.ccrcc import Ccrcc
     34 from cptac.cancers.coad import Coad

~\anaconda3\lib\site-packages\cptac\cancers\brca.py in <module>
     10 #   limitations under the License.
     11 
---> 12 from cptac.cancers.cancer import Cancer
     13 
     14 # Import various BRCA data sources

~\anaconda3\lib\site-packages\cptac\cancers\cancer.py in <module>
     23 from cptac.tools.dataframe_tools import add_index_levels, join_col_to_dataframe
     24 
---> 25 class Cancer:
     26     NORMAL_ENDINGS = ('.N', '.C') # HNSCC data has cored normal samples marked .C
     27     """Note that all cancer datasets are class objects that inherit 

~\anaconda3\lib\site-packages\cptac\cancers\cancer.py in Cancer()
   1000         return df
   1001 
-> 1002     def _format_mutations_data(self, mutations: pd.DataFrame, mutations_were_filtered: bool, show_location: bool=True, how: str="outer", quiet: bool=False, tissue_type: str="both", mutation_cols: list[str] or str=["Mutation","Location"]
   1003                                ) -> pd.DataFrame:
   1004         """Format mutations data. Add a Sample_Status column, fill in NaNs with Wildtype_Normal or Wildtype_Tumor.

TypeError: 'type' object is not subscriptable

**Comment by sabmel** [comment]
I'm so sorry about the inconvenience. Would you mind letting us know what version of cptac you are currently running?

**Comment by janamace** [comment]
Hi Sabrina,

Thank you for your answer! I'm using these versions of cptac, pandas, and, pip, conda, and numexpr:

numexpr                            2.7.3
cptac                              1.5.1
conda                              4.14.0
pandas                             2.0.3
pip                                23.2.1

**Comment by sabmel** [comment]
Thank you! I'm not entirely sure why it's throwing that error for you, but
we just released a new update, so go ahead and update and see if the issue
persists. I appreciate your patience!
