### ISSUE TITLE
The UCEC umich acetylproteomics data are note a suitable data frame formatThe ucec umich acetylproteomics data are note a suitable data frame format

### ISSUE THREAD

**Issue by zihaoxingstudy1** [PayneLab/cptac#46]
The ucec umich acetylproteomics data are note a suitable data frame format,and there are variable names in the middle of the file.
![cptac3.png](https://github.com/PayneLab/cptac/assets/58220227/edbc2d3d-04cc-4f56-bef3-3a1cf3e9dd5d)

**Comment by bm600** [comment]
Thanks for letting us know! We've just updated the package to v1.5.4 and this error is no longer there. If anything else comes us please let us know. Thank you!
