### ISSUE TITLE
HttpResponseError on import

### ISSUE THREAD

**Issue by DennisGankin** [PayneLab/cptac#47]
Hey, 
on calling `import cptac` I get the following error:

```HttpResponseError: Requesting data failed with the following error: 404 Client Error: NOT FOUND for url: https://zenodo.org/api/records/7897498```

Is the zenodo API link outdated?
Thanks for your help in advance.

**Comment by sgosline** [comment]
I am getting the same error.

**Comment by sabmel** [comment]
Hello! It looks like Zenodo released a new update that is causing some issues. We are looking into adjusting our code or seeing if there is an error on Zenodo's end. I appreciate your patience!

**Comment by bm600** [comment]
Hey thanks for using cptac everyone! Zenodo updated their API and we've just modified our download functions to be able to comply with it. We've just released v1.5.5 and it should solve the problem. If you have any more issues please let us know. Thank you

**Comment by sgosline** [comment]
I have a related error, now when I do the import I get this:
cptac error: ERROR: 'filename' (/Users/gosl241/Library/CloudStorage/OneDrive-PNNL/Documents/GitHub/candleDataProcessing/build/cptac/getCptacData.py, line 6)

(line 6 is where i call import cptac). Any ideas?
