### ISSUE TITLE
Tutorial 6: Easy integration with R link broken

### ISSUE THREAD

**Issue by crazyhottommy** [PayneLab/cptac#48]
Hi, 
the R integration link is broken. Can you please fix that?

Thanks!
Tommy

**Comment by samuelpayne** [comment]
What do you mean? Like is the reticulate package not working for you?
The tutorial for this is - https://github.com/PayneLab/cptac/blob/master/notebooks/tutorial06_cptac_in_R.Rmd

**Comment by crazyhottommy** [comment]
https://paynelab.github.io/cptac/tutorial06_cptac_in_R.html I mean this link is broken.

**Comment by sabmel** [comment]
Hello! We've updated the tutorial and link, and they should be available very soon in the next release. I appreciate your patience!
