### ISSUE TITLE
Tissue source center

### ISSUE THREAD

**Issue by sebastianffx** [PayneLab/cptac#55]
Thank you for this nice piece of software!

I am trying to generate splits for a experiment using the whole slide images of LSCC, but I can not find the info of what is the source of the data, akin to the TCGA tissue source site codes: https://gdc.cancer.gov/resources-tcga-users/tcga-code-tables/tissue-source-site-codes 

Or is such information just not available?

Thank you!

**Comment by samuelpayne** [comment]
I do not believe that the tissue source site is tracked (e.g. hospital name). We only track country of origin for the samples.
