### ISSUE TITLE
FFPE vs Frozen tissue filter

### ISSUE THREAD

**Issue by sebastianffx** [PayneLab/cptac#56]
Hello,
Thanks for the work in the library!

Is there a way to add filter the image ids of the pathology slides that are formalin-fixed, paraffin-embedded (FFPE) or frozen tissue?

Thank you!

Sebastian

**Comment by samuelpayne** [comment]
So, all the images are stored on the Cancer Imaging Archive, and the specifics of the meta-data for tissue processing prior to imaging would be stored there, and not part of our meta-data.

As a potential other answer, all tissue in CPTAC is acquired fresh frozen. The proteomics/genomics data is from fresh frozen tissue. I am not sure if the imaging data used a piece that was FFPE.
