### ISSUE TITLE
version question

### ISSUE THREAD

**Issue by Cp0728** [PayneLab/cptac#59]
If I have a previous version of 1.5.10 and I haven't updated the latest version, will the old version not be available? If I update then what are the dependencies and what is the version of python

**Comment by sabmel** [comment]
Some people ran into problem with importing in the previous version, so I would recommend updating to the newest version. The dependencies should be automatically checked/updated on import, but here they are for convenience. Please let me know if this didn't answer your question: `		'numpy>=1.16.3',
		'pandas>=2.0.0',
		'requests>=2.21.0',
		'scipy>=1.10.0',
		'openpyxl>=2.6.0',
		'statsmodels>=0.10.0',
		'pyranges>=0.0.111',
        'tqdm>=4.65.0',
 python_requires='>=3.6'. `

**Comment by Cp0728** [comment]
When my dependencies are met, updating cptac encounters (ERROR: Could not find a version that satisfies the requirement cptac==1.5.11 (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.5, 0.5.0, 0.5.1, 0.5.2, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.5, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 1.0.0rc1, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.5.0rc1, 1.5.0rc3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10)
ERROR: No matching distribution found for cptac==1.5.11）
This gives the question
