### ISSUE TITLE
v1.5.11 not available on pip

### ISSUE THREAD

**Issue by srrajapurkar** [PayneLab/cptac#62]
Hi,
While the github page states v1.5.11 has been released with the import bug fix, it is not available through pip. I get an error while installing v1.5.11 manually. I am using Python v3.9

`pip install cptac==1.5.11
ERROR: Could not find a version that satisfies the requirement cptac==1.5.11 (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.5, 0.5.0, 0.5.1, 0.5.2, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.5, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 1.0.0rc1, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.5.0rc1, 1.5.0rc3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10)
ERROR: No matching distribution found for cptac==1.5.11`

PYPI website also states the latest version is 1.5.10 (https://pypi.org/project/cptac/). Not sure if the update got pushed out.

**Comment by srrajapurkar** [comment]
I can install v1.5.11 now. However the "value error" bug still seems to persist in this version.

<img width="1144" alt="image" src="https://github.com/PayneLab/cptac/assets/22772454/a55c37b7-1c2d-46a5-af4f-a2367c902256">

**Comment by bm600** [comment]
Hello! We were having some pip problems but it should be all updated now with the latest version
