### ISSUE TITLE
why don't you analyze some gastric cancer in CPTAC ?

### ISSUE THREAD

**Issue by zihaoxingstudy1** [PayneLab/cptac#8]
there are also  some gastric cancer can be analyzed in CPTAC

**Comment by samuelpayne** [comment]
Hello,

this package is created currently for just CPTAC data, which does not include gastric cancer. I do know that other groups have created proteogenomic data for gastric cancer (https://pubmed.ncbi.nlm.nih.gov/30645970), but that it outside the current scope of our tool. If you are part of this group, we'd be interested in chatting

**Comment by samuelpayne** [comment]
i mean the Korean group that did the gastric cancer paper

**Comment by zihaoxingstudy1** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hello Sam , thanks you tell me this, i am also interested in gastric cancer , i  just learn how to analyze the CPTAC data, i download the raw data of the cptac web site and i saw there are some gastric cancer's data i can download. 
        i am very glad to chat with you about bioinformatics and CPTAC data analyze. :>)
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                zihaoxing
                            
                    
                        
                            
                                    zihaoxing@stu2019.jnu.edu.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 5/25/2020 22:39，Sam Payne<notifications@github.com> wrote： 



i mean the Korean group that did the gastric cancer paper

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by samuelpayne** [comment]
That data is by a Korean group, affiliated with the International Cancer Proteogenomics Consortium. The CPTAC dcc hosts their data. But our python module current does not.
