### ISSUE TITLE
why the CPTAC patients' id is different from TCGA's patient id?

### ISSUE THREAD

**Issue by zihaoxingstudy1** [PayneLab/cptac#9]
why the CPTAC patients' id is different from TCGA's patient id?

**Comment by caleb-lindgren** [comment]
The data from CPTAC comes from a different group of people than the TCGA data. Because the samples come from different people, they have different patient IDs.

**Comment by caleb-lindgren** [comment]
If you'd like to learn more about the CPTAC project, this website is a good place to start: https://proteomics.cancer.gov/programs/cptac

For comparison, here is the TCGA website: https://www.cancer.gov/about-nci/organization/ccg/research/structural-genomics/tcga

They are separate programs that use samples from different groups of people. If you have more questions feel free to ask.
